apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: odigos-data-collection
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes/stats
      - nodes/proxy
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - apps
    resources:
      - replicasets
    verbs:
      - list
      - watch
      - get