autoscaler:
  image:
    repository: keyval/odigos-autoscaler
    tag: v0.1.63

scheduler:
  image:
    repository: keyval/odigos-scheduler
    tag: v0.1.63

ui:
  image:
    repository: keyval/odigos-ui
    tag: v0.1.63
    port: 3001

instrumentor:
  deleteLangDetectionPods: true
   # Ignored namespaces won't show up in odigos-ui
  ignoredNamespaces:
    - odigos-system
    - kube-system
    - local-path-storage
    - istio-system
    - linkerd
  image:
    repository: keyval/odigos-instrumentor
    tag: v0.1.63

odiglet:
  image:
    repository: keyval/odigos-odiglet
    tag: v0.1.63

telemetry:
  enabled: true
