imagePullSecrets: []

image:
  prefix: null

autoscaler:
  image:
    repository: keyval/odigos-autoscaler
  nodeSelector:
    kubernetes.io/os: linux
  tolerations: []
  affinity: {}

scheduler:
  image:
    repository: keyval/odigos-scheduler
  nodeSelector:
    kubernetes.io/os: linux
  tolerations: []
  affinity: {}

instrumentor:
  deleteLangDetectionPods: true
  # Ignored namespaces won't show up in odigos-ui
  ignoredNamespaces:
    - odigos-system
    - kube-system
    - local-path-storage
    - istio-system
    - linkerd
  image:
    repository: keyval/odigos-instrumentor
  nodeSelector:
    kubernetes.io/os: linux
  tolerations: []
  affinity: {}

odiglet:
  image:
    repository: keyval/odigos-odiglet
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - effect: NoSchedule
      key: node.kubernetes.io/os
      operator: Equal
      value: windows
  affinity: {}

# Pod Security Policy
psp:
  enabled: false

telemetry:
  enabled: true
