## @param nodeSelector Node labels for autoscaler, scheduler, ui, instrumentor pods assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

autoscaler:
  image:
    repository: keyval/odigos-autoscaler
    tag: v0.1.63
  nodeSelector: {}
  

scheduler:
  image:
    repository: keyval/odigos-scheduler
    tag: v0.1.63
  nodeSelector: {}

ui:
  image:
    repository: keyval/odigos-ui
    tag: v0.1.63
  nodeSelector: {}

instrumentor:
  deleteLangDetectionPods: true
   # Ignored namespaces won't show up in odigos-ui
  ignoredNamespaces:
    - odigos-system
    - kube-system
    - local-path-storage
    - istio-system
    - linkerd
  image:
    repository: keyval/odigos-instrumentor
    tag: v0.1.63
  nodeSelector: {}

odiglet:
  image:
    repository: keyval/odigos-odiglet
    tag: v0.1.63

telemetry:
  enabled: true
