---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odigos-ui
  namespace: {{ .Release.Namespace }}
  annotations:
    odigos.io/skip: "true"
  labels:
    app: odigos-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odigos-ui
  template:
    metadata:
      labels:
        app: odigos-ui
    spec:
      serviceAccount: odigos-ui
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 6 }}
{{- end }}
      containers:
        - name: odigos-ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          env:
            - name: CURRENT_NS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: ui
              containerPort: {{- if .Values.ui.image.port }} {{ .Values.ui.image.port }} {{- else }} 3000 {{- end }}              
      nodeSelector:
        kubernetes.io/os: linux